/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginDokterRouteImport } from './routes/login-dokter'
import { Route as LoginAdminRouteImport } from './routes/login-admin'
import { Route as KonsultanRouteImport } from './routes/konsultan'
import { Route as JanjiSayaRouteImport } from './routes/janji-saya'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as IndexRouteImport } from './routes/index'

const LoginDokterRoute = LoginDokterRouteImport.update({
  id: '/login-dokter',
  path: '/login-dokter',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginAdminRoute = LoginAdminRouteImport.update({
  id: '/login-admin',
  path: '/login-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const KonsultanRoute = KonsultanRouteImport.update({
  id: '/konsultan',
  path: '/konsultan',
  getParentRoute: () => rootRouteImport,
} as any)
const JanjiSayaRoute = JanjiSayaRouteImport.update({
  id: '/janji-saya',
  path: '/janji-saya',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/janji-saya': typeof JanjiSayaRoute
  '/konsultan': typeof KonsultanRoute
  '/login-admin': typeof LoginAdminRoute
  '/login-dokter': typeof LoginDokterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/janji-saya': typeof JanjiSayaRoute
  '/konsultan': typeof KonsultanRoute
  '/login-admin': typeof LoginAdminRoute
  '/login-dokter': typeof LoginDokterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/janji-saya': typeof JanjiSayaRoute
  '/konsultan': typeof KonsultanRoute
  '/login-admin': typeof LoginAdminRoute
  '/login-dokter': typeof LoginDokterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking'
    | '/janji-saya'
    | '/konsultan'
    | '/login-admin'
    | '/login-dokter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking'
    | '/janji-saya'
    | '/konsultan'
    | '/login-admin'
    | '/login-dokter'
  id:
    | '__root__'
    | '/'
    | '/booking'
    | '/janji-saya'
    | '/konsultan'
    | '/login-admin'
    | '/login-dokter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingRoute: typeof BookingRoute
  JanjiSayaRoute: typeof JanjiSayaRoute
  KonsultanRoute: typeof KonsultanRoute
  LoginAdminRoute: typeof LoginAdminRoute
  LoginDokterRoute: typeof LoginDokterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login-dokter': {
      id: '/login-dokter'
      path: '/login-dokter'
      fullPath: '/login-dokter'
      preLoaderRoute: typeof LoginDokterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-admin': {
      id: '/login-admin'
      path: '/login-admin'
      fullPath: '/login-admin'
      preLoaderRoute: typeof LoginAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konsultan': {
      id: '/konsultan'
      path: '/konsultan'
      fullPath: '/konsultan'
      preLoaderRoute: typeof KonsultanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/janji-saya': {
      id: '/janji-saya'
      path: '/janji-saya'
      fullPath: '/janji-saya'
      preLoaderRoute: typeof JanjiSayaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingRoute: BookingRoute,
  JanjiSayaRoute: JanjiSayaRoute,
  KonsultanRoute: KonsultanRoute,
  LoginAdminRoute: LoginAdminRoute,
  LoginDokterRoute: LoginDokterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
